model_name: mlpvae_mdn_dp2_v22_lsst_gaap1p0_zprior_nozweight_zpointrisk_lamprior1_faintw1_bestoutlier
data_source: dp2_parquet
train_parquet: /astro/users/lindajin/obs_catalog/data/415_clipped_train_rtn124_parquet_0103491bd9870eb3d19bd89fa6cd57a9/train_clipped_v3.parquet
test_parquet: /astro/users/lindajin/obs_catalog/data/412_som_test_rtn124_parquet_80763a5a141d268b7c6ed332ab552fbd/test_som_mc_matched_v3.parquet
val_frac: 0.1
z_max_train: null
use_colors: true
use_euclid: false
use_gaap: true
standardize: true
double_precision: false
epochs: 600
batch: 256
lr: 0.001
lam_z: 20.0
lam_z_min: 20.0
lam_z_restore: 50
lam_r: 0.1
sigma_floor: 0.3
warmup_epochs: 60
phase2_vae_lr_frac: 1.0
grad_clip_max_norm: 2.0
z_weight_cap: 10.0
init_from: /astro/users/lindajin/photoz_mlpvae/trained/mlpvae_synth_zsep_v3_no_euclid_gaap1p0/best.pt
beta_max: 0.1
beta_epochs: 50
recon_ramp: 50
instant_lam_r_beta: false
patience: 120
seed: 42
device: cuda
n_zbins_weight: 25
speculator_dir: /astro/users/lindajin/speculator/trained/Inoue_IGM
filter_dir: /astro/users/lindajin/obs_catalog/filters
training_scheme: always sigma_NMAD for best model
model_version: mdn
best_criterion: outlier
bias_scale: 0.003
nmad_scale: 0.02
zred_sigma_floor: 0.01
zred_sigma_floor_frac: null
zprior_from_ckpt: null
z_head_weight_decay: 0.001
allow_vae_grad: false
lam_prior: 1.0
centered_z_scale: false
use_z_prior_sampling: false
z_sample_method: risk
