model_name: mlpvae_v9_lsst_gaap1p0
data_source: hdf5_presplit
train_hdf5: /astro/users/lindajin/obs_catalog/data/83_training_v4_match_ecdfs_sitcomtn154_27184412354f233d1b9f512bdf350d58/dp1_matched_v4_train.hdf5
test_hdf5: /astro/users/lindajin/obs_catalog/data/84_test_v4_match_ecdfs_sitcomtn154_1ec71937ff3e4a0a8283535193764ec7/dp1_matched_v4_test.hdf5
val_frac: 0.1
use_colors: true
use_euclid: false
use_gaap: true
epochs: 500
batch: 256
lr: 0.0001
lam_z: 20.0
lam_z_min: 20.0
lam_z_restore: 50
lam_r: 0.1
sigma_floor: 0.3
warmup_epochs: 50
sigma_z_warmup: 0
phase2_trunk_lr_frac: 1.0
phase2_vae_lr_frac: 1.0
z_weight_cap: 10.0
init_from: /astro/users/lindajin/photoz_mlpvae/trained/mlpvae_synth_v7_no_euclid_gaap1p0/best.pt
beta_max: 0.1
beta_epochs: 50
recon_ramp: 50
patience: 100
seed: 42
device: cuda
n_zbins_weight: 25
speculator_dir: /astro/users/lindajin/speculator/trained/Inoue_IGM
filter_dir: /astro/users/lindajin/obs_catalog/filters
training_scheme: always sigma_NMAD for best model
