"""
train_synth.py
==============
Train PhotozMLPVAE on **synthetic SEDs** generated by the Speculator/FSPS
surrogate, where the true SPS parameters are known.

Unlike train.py (which uses real LSST+Euclid photometry with unknown SPS
parameters), this script:

  1. Loads true 16-dim SPS parameters from sed_generation/data/sed_*.h5.
  2. Runs the frozen Speculator + FilterConv forward pass to get noiseless
     AB magnitudes in all 10 bands.
  3. Assigns synthetic photometric uncertainties (LSST DP1 + Euclid ERO depths).
     Magnitudes stay noiseless so the frozen decoder's reconstruction of the
     true SED falls exactly on the input photometry.
  4. Trains the MLPVAE with the same Phase-1 / Phase-2 schedule as train.py.
  5. At evaluation, passes the known true SPS parameters (theta_true, shape
     N_gal × 16) to plot_corner_posteriors so ALL 16 parameter truth values
     appear as gold lines on the corner plots.

Noise model
-----------
  For each band b with 5σ limiting magnitude m_5σ[b]:

      SNR_phot = 5 × 10^{−0.4 (m − m_5σ)}
      σ_m      = sqrt( (2.5 / (ln10 × SNR_phot))^2 + σ_cal^2 )

  A band is "detected" (mask = 1) when the noiseless mag satisfies
  0 < m < 35 and the computed σ_m is finite and positive — mirroring the
  criterion used by _raw_mags_errs_mask for real data.
  Approximate depths used (can be overridden via --m5sig):
      LSST u/g/r/i/z/y : 25.0 / 26.5 / 26.3 / 25.7 / 25.0 / 23.4
      Euclid VIS/Y/J/H : 25.5 / 24.0 / 24.0 / 24.0

Usage
-----
    conda run -n WL_ML_Challenge python photoz_mlpvae/scripts/train_synth.py
    conda run -n WL_ML_Challenge python photoz_mlpvae/scripts/train_synth.py \\
        --model-name mlpvae_synth_v1 --n-train 200000

Outputs  (photoz_mlpvae/trained/<MODEL_NAME>/)
---------------------------------------------
  best.pt
  config.yaml
  train.log
  train_curves.png
  test_scatter.png
  test_predictions.csv        z_true, z_pred, z_std, delta_z, + 16 theta cols
  test_metrics_paper_style.png
  test_pit.png
  corner_<label>.png          corner plots with ALL 16 true SPS params marked
"""

import os, sys, time, argparse, warnings, yaml, datetime, h5py
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

_BASE = "/astro/users/lindajin"
sys.path.insert(0, _BASE)

from obs_catalog.dataloader import (
    build_features, compute_z_weights, make_dataloader,
    MAG_COLS, ERR_COLS, LSST_MAG_COLS, LSST_ERR_COLS, TARGET_COL,
    GAAP_MAG_COLS, GAAP_ERR_COLS, LSST_GAAP_MAG_COLS, LSST_GAAP_ERR_COLS,
)
from photoz_utils import (
    plot_scatter, plot_redshift_hist, plot_metrics_vs_zpred,
    plot_metrics_paper_style, plot_pit,
    plot_corner_posteriors, plot_sed_reconstructions,
    compute_metrics,
)
warnings.filterwarnings("ignore")


# ─────────────────────────────────────────────────────────────────────────────
# Adjustables
# ─────────────────────────────────────────────────────────────────────────────

MODEL_NAME     = "mlpvae_synth_v1"
SYNTH_TRAIN_H5 = os.path.join(_BASE, "sed_generation", "data", "sed_train.h5")
SYNTH_VAL_H5   = os.path.join(_BASE, "sed_generation", "data", "sed_val.h5")
SPECULATOR_DIR = os.path.join(_BASE, "speculator", "trained", "Inoue_IGM")
FILTER_DIR     = os.path.join(_BASE, "obs_catalog", "filters")
OUT_BASE       = os.path.join(_BASE, "photoz_mlpvae", "trained")

USE_COLORS     = True
USE_GAAP       = False   # True → GAAP 1.0-arcsec aperture mags for LSST bands

# Number of synthetic samples to use from each HDF5 file.
# sed_train.h5 has 2M rows; sed_val.h5 has 100K rows (split 80/20 → val/test).
N_TRAIN_MAX = 200_000
N_VAL_MAX   =  80_000
N_TEST_MAX  =  20_000   # taken as the last N_TEST_MAX rows of sed_val.h5

SEED = 42

# ── Survey noise model: 5σ AB limiting magnitudes ────────────────────────────
# LSST DP1 (~1 yr, ECDFS field) + Euclid ERO depths (approximate)
M_5SIG = np.array([
    26.4,27.8,27.1,26.7,25.8,24.6,  # LSST u, g, r, i, z, y (Zhang, 2025) Gaap1p0 of the ECDFS field
    25.5, 24.0, 24.0, 24.0,                # Euclid VIS, Y, J, H
], dtype=np.float32)

CALIB_FLOOR       = 0.01   # photometric calibration floor (mag)
I_BAND_SNR_MIN    = 5.0    # minimum i-band SNR for galaxy inclusion (None = no cut)

# ── Training hyper-parameters ─────────────────────────────────────────────────
MAX_EPOCHS    = 500
BATCH_SIZE    = 512
LR            = 1e-4
PATIENCE      = MAX_EPOCHS // 5
WARMUP_EPOCHS = 50
RECON_RAMP    = 50
BETA_EPOCHS   = 50
DEVICE        = "cuda" if torch.cuda.is_available() else "cpu"

LAM_Z          = 20.0
LAM_Z_MIN      = 2.0   #  λ_z drop at Phase 2 start (matches train_dp1 default)
LAM_Z_RESTORE  = 50     # epochs to ramp λ_z back to full after β stabilises
LAM_R          = 0.3    # noiseless synthetic data; softer than real-data 0.1
BETA_MAX       = 0.1
SIGMA_FLOOR    = 0.3
N_ZBINS_WEIGHT = 25

# Phase 2 LR — match train_dp1: keep trunk at full LR, add vae_head at full LR.
# (The old PHASE2_LR_FRAC=0.1 crushed both to 1e-5 and prevented VAE learning.)
PHASE2_TRUNK_LR_FRAC = 0.1   # protect trunk from noiseless recon gradient
PHASE2_VAE_LR_FRAC   = 1.0
NMAD_AVG_WINDOW      = 5    # rolling-average window for checkpoint criterion

# Up-weight high-z galaxies during training to prevent trunk collapse on
# band-dropout sources (Lyman break pushes many features to fill values).
Z_BOOST_THRESHOLD = 3.0
Z_BOOST_FACTOR    = 5.0

# SPS parameter names in theta_full (must match photoz_mlpvae.PARAM_NAMES)
PARAM_NAMES_FULL = [
    "zred", "logmass", "logzsol", "dust2", "dust1_fraction", "dust_index",
    "gas_logz", "fagn", "agn_tau", "igm_scale",
    "logsfr_ratios_0", "logsfr_ratios_1", "logsfr_ratios_2",
    "logsfr_ratios_3", "logsfr_ratios_4", "logsfr_ratios_5",
]


# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────

class _Tee:
    def __init__(self, stream, fpath):
        self._stream = stream
        self._file   = open(fpath, "a", buffering=1)

    def write(self, data):
        self._stream.write(data)
        self._file.write(data)

    def flush(self):
        self._stream.flush()
        self._file.flush()

    def close(self):
        self._file.close()

    def __getattr__(self, attr):
        return getattr(self._stream, attr)


# ─────────────────────────────────────────────────────────────────────────────
# Metrics
# ─────────────────────────────────────────────────────────────────────────────

def sigma_nmad(z_pred, z_true):
    dz  = (z_pred - z_true) / (1.0 + z_true)
    med = np.nanmedian(dz)
    return 1.4826 * np.nanmedian(np.abs(dz - med))


def outlier_frac(z_pred, z_true, threshold=0.15):
    dz = np.abs((z_pred - z_true) / (1.0 + z_true))
    return float(np.nanmean(dz > threshold))


def rms_dz(z_pred, z_true):
    dz = (z_pred - z_true) / (1.0 + z_true)
    return float(np.sqrt(np.nanmean(dz[np.isfinite(dz)] ** 2)))


# ─────────────────────────────────────────────────────────────────────────────
# Loss-curve plot
# ─────────────────────────────────────────────────────────────────────────────

def plot_curves(history: dict, path: str, events: list = None):
    """
    Two-row layout: one wide total-loss panel on top, four breakdown panels below.
    events: list of (epoch_index, label) for phase/lambda change annotations.
    """
    import matplotlib.gridspec as gridspec

    fig = plt.figure(figsize=(20, 7))
    gs  = gridspec.GridSpec(2, 4, figure=fig, height_ratios=[1.4, 1],
                            hspace=0.35, wspace=0.3)
    ax_top  = fig.add_subplot(gs[0, :])
    ax_subs = [fig.add_subplot(gs[1, i]) for i in range(4)]

    keys   = ["total", "z_sup", "recon", "kl", "log_sigma_z"]
    labels = ["Total loss", "z NLL", "Reconstruction", "KL", "mean log σ_z"]

    prop_cycle = plt.rcParams["axes.prop_cycle"].by_key()["color"]
    event_colors = [prop_cycle[(i + 2) % len(prop_cycle)]
                    for i in range(len(events) if events else 0)]

    def _draw_events(ax, label_in_legend):
        if not events:
            return
        for (x, lbl), color in zip(events, event_colors):
            ax.axvline(x, ls=":", color=color, lw=1.4,
                       label=f"ep {x}: {lbl}" if label_in_legend else None)

    # ── Top: total loss ──────────────────────────────────────────────────────
    k, lab = "total", labels[0]
    if f"tr_{k}" in history and history[f"tr_{k}"]:
        ax_top.plot(history[f"tr_{k}"],  label="train")
        ax_top.plot(history[f"val_{k}"], label="val", ls="--")
    _draw_events(ax_top, label_in_legend=True)
    ax_top.set_title(lab, fontsize=12)
    ax_top.set_xlabel("epoch")
    ax_top.legend(fontsize=9, loc="upper right")

    # ── Bottom: breakdown losses ─────────────────────────────────────────────
    for ax, k, lab in zip(ax_subs, keys[1:], labels[1:]):
        if f"tr_{k}" in history and history[f"tr_{k}"]:
            ax.plot(history[f"tr_{k}"],  label="train")
            ax.plot(history[f"val_{k}"], label="val", ls="--")
        _draw_events(ax, label_in_legend=False)
        ax.set_title(lab, fontsize=10)
        ax.set_xlabel("epoch")
        ax.legend(fontsize=7)

    fig.savefig(path, dpi=120, bbox_inches="tight")
    plt.close(fig)
    print(f"  Curves → {path}")


# ─────────────────────────────────────────────────────────────────────────────
# Training loop
# ─────────────────────────────────────────────────────────────────────────────

def run_epoch(model, loader, device, opt=None,
              lam_z=LAM_Z, lam_r=LAM_R, beta=0.0,
              sigma_floor=SIGMA_FLOOR, use_nll_z=True):
    """One train or validation epoch. Returns dict of mean losses."""
    is_train = (opt is not None)
    model.train() if is_train else model.eval()

    totals = {k: 0.0 for k in ("total", "z_sup", "recon", "kl", "log_sigma_z")}
    n = 0

    ctx = torch.enable_grad if is_train else torch.no_grad

    with ctx():
        for x_b, mags_b, errs_b, mask_b, z_b, zw_b in loader:
            x_b    = x_b.to(device)
            mags_b = mags_b.to(device)
            errs_b = errs_b.to(device)
            mask_b = mask_b.to(device)
            z_b    = z_b.to(device)
            zw_b   = zw_b.to(device)

            if is_train:
                opt.zero_grad()

            losses = model.loss(
                x_b, mags_b, errs_b, mask_b, z_b,
                lam_z=lam_z, lam_r=lam_r, beta=beta,
                sigma_floor=sigma_floor,
                z_weights=zw_b,
                use_nll_z=use_nll_z,
            )

            if is_train:
                losses["total"].backward()
                torch.nn.utils.clip_grad_norm_(model.encoder.parameters(), 2.0)
                opt.step()

            bs = len(x_b)
            for k in totals:
                totals[k] += losses[k].item() * bs
            n += bs

    return {k: v / n for k, v in totals.items()}


# ─────────────────────────────────────────────────────────────────────────────
# Synthetic data utilities
# ─────────────────────────────────────────────────────────────────────────────

def load_theta_hdf5(h5path, n_max, rng, start_row=0):
    """
    Load SPS parameters from an HDF5 file and (optionally) subsample.

    Parameters
    ----------
    h5path    : str
    n_max     : int or None  maximum number of rows to return
    rng       : np.random.Generator
    start_row : int          first row to consider (for val/test splitting)

    Returns
    -------
    theta : (N, 16) float32 array of physical SPS parameters
    """
    with h5py.File(h5path, "r") as f:
        n_total = f["parameters"].shape[0]
        available = n_total - start_row
        if n_max is None or n_max >= available:
            end_row = n_total
        else:
            end_row = start_row + n_max
        # Contiguous slice — far faster than fancy/random indexing on large HDF5 files.
        # Synthetic data is already randomly ordered so order-based selection is fine.
        theta = f["parameters"][start_row:end_row].astype(np.float32)
    return theta


def generate_photometry_gpu(theta, model_dec, device, batch_size=1024):
    """
    Run true SPS parameters through the frozen Speculator + FilterConv to
    obtain noiseless AB magnitudes.

    Parameters
    ----------
    theta     : (N, 16) float32 numpy array – physical SPS parameters
                  [zred, logmass, logzsol, dust2, dust1_fraction, dust_index,
                   gas_logz, fagn, agn_tau, igm_scale, logsfr_ratios_0..5]
    model_dec : PhotozMLPVAE instance (only decoder is used; must be on device)
    device    : str

    Returns
    -------
    mags_noiseless : (N, 10) float32 – noiseless AB magnitudes
    """
    model_dec.eval()
    mags_list = []
    n = theta.shape[0]
    for i in range(0, n, batch_size):
        theta_b = torch.from_numpy(theta[i:i + batch_size]).to(device)
        with torch.no_grad():
            log_spec, _ = model_dec.speculator(theta_b)
            m_ab = model_dec.filter_conv(
                log_spec, theta_b[:, 0], theta_b[:, 1]
            )   # (batch, 10)
        mags_list.append(m_ab.cpu().numpy())
    return np.concatenate(mags_list, axis=0).astype(np.float32)   # (N, 10)


def add_photometric_errors(mags_noiseless,
                           m5sig=None, calib_floor=CALIB_FLOOR,
                           i_band_snr_min=I_BAND_SNR_MIN):
    """
    Assign synthetic photometric uncertainties WITHOUT adding Gaussian noise.

    Because the decoder is the same Speculator used to generate the data, the
    noiseless magnitudes are kept as 'observed' photometry so that the
    reconstruction of the true SED at z_true falls exactly on the input
    photometry.  Only the uncertainty (σ_m) is computed from the noise model:

        SNR_phot = 5 × 10^{−0.4 (m − m_5σ)}   (per-band)
        σ_m      = sqrt( (2.5 / (ln10 × SNR_phot))^2 + calib_floor^2 )

    Detection criterion mirrors _raw_mags_errs_mask for real data:
        m_ok = 0 < m < 35 and finite
        e_ok = σ_m > 0 and finite
        detected = m_ok & e_ok

    Parameters
    ----------
    mags_noiseless : (N, B) float32
    m5sig          : (B,) float32 – 5σ limiting magnitudes; defaults to M_5SIG
    calib_floor    : float – calibration noise floor in magnitudes
    i_band_snr_min : float or None – minimum i-band (index 3) SNR for a galaxy
                     to be included; None or 0 disables the cut

    Returns
    -------
    mags_out : (N, B) float32  NaN where undetected (noiseless otherwise)
    errs     : (N, B) float32  NaN where undetected
    mask     : (N, B) float32  1 = detected, 0 = undetected
    gal_keep : (N,)   bool     True for galaxies passing the i-band SNR cut
    """
    if m5sig is None:
        m5sig = M_5SIG
    m5sig = np.asarray(m5sig, dtype=np.float32)[None, :]   # (1, B)

    snr_phot = 5.0 * np.power(10.0, -0.4 * (mags_noiseless - m5sig))

    # Galaxy-level i-band SNR cut (use raw SNR before clipping)
    if i_band_snr_min:
        gal_keep = snr_phot[:, 3] >= i_band_snr_min
    else:
        gal_keep = np.ones(len(mags_noiseless), dtype=bool)

    snr_phot = np.clip(snr_phot, 1e-3, None)                # avoid /0

    sig_phot = (2.5 / np.log(10.0)) / snr_phot
    errs     = np.sqrt(sig_phot ** 2 + calib_floor ** 2).astype(np.float32)

    # Mirror the real-data detection criterion in _raw_mags_errs_mask
    m_ok     = np.isfinite(mags_noiseless) & (mags_noiseless > 0) & (mags_noiseless < 35)
    e_ok     = np.isfinite(errs) & (errs > 0)
    detected = m_ok & e_ok
    mask     = detected.astype(np.float32)

    mags_out = mags_noiseless.copy()
    mags_out[~detected] = np.nan
    errs[~detected]     = np.nan

    return mags_out, errs, mask, gal_keep


def mags_to_dataframe(mags, errs, z_spec, mag_cols=MAG_COLS, err_cols=ERR_COLS):
    """
    Build a pandas DataFrame with the column names expected by build_features.

    Parameters
    ----------
    mags     : (N, B) float32  noisy AB mags  (NaN = undetected)
    errs     : (N, B) float32  mag errors     (NaN = undetected)
    z_spec   : (N,)   float32  true redshifts
    mag_cols : list of B magnitude column names  (default: all 10 bands)
    err_cols : list of B error column names      (default: all 10 bands)

    Returns
    -------
    df : pd.DataFrame  with columns mag_cols + err_cols + [TARGET_COL]
    """
    data = {}
    for j, (mc, ec) in enumerate(zip(mag_cols, err_cols)):
        data[mc] = mags[:, j]
        data[ec] = errs[:, j]
    data[TARGET_COL] = z_spec
    return pd.DataFrame(data)


# ─────────────────────────────────────────────────────────────────────────────
# Feature degeneracy fix
# ─────────────────────────────────────────────────────────────────────────────

def append_detection_features(X: np.ndarray, mask: np.ndarray) -> np.ndarray:
    """
    Append 2 detection-rate features to the 40-dim encoder input.

    The trunk collapses high-z galaxies to a single representation because
    their Lyman-break band-dropouts produce near-identical 40-dim feature
    vectors: detected bands have similar colours, non-detected bands carry
    only the sentinel/flag pattern.  Providing the *count* of detected bands
    explicitly breaks this degeneracy without requiring the ResBlock to
    reverse-engineer it from 20 missingness flags.

    Columns appended (both in [0, 1], no additional scaling needed):
      D+0: frac_detected      = n_bands_detected / B  (B = total bands in mask)
           Overall photometry coverage; discriminates sparse from rich SEDs.
      D+1: frac_blue_detected = (u + g + r detected) / 3
           Lyman-break proxy: 0 → all three blue LSST bands missing (z > ~4.5);
           0.33 → only u missing (z > ~2); 1 → fully blue-detected (z < ~2).

    Parameters
    ----------
    X    : (N, D)   float32  encoder features from build_features
    mask : (N, 10)  float32  band-presence mask (1=detected) from build_features

    Returns
    -------
    X_out : (N, D+2) float32
    """
    frac_det  = mask.mean(axis=1, keepdims=True)        # (N, 1)  all 10 bands
    frac_blue = mask[:, :3].mean(axis=1, keepdims=True) # (N, 1)  u, g, r only
    return np.concatenate([X, frac_det, frac_blue], axis=1).astype(np.float32)


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Train PhotozMLPVAE on synthetic SEDs with known SPS params."
    )
    parser.add_argument("--model-name",    default=MODEL_NAME)
    parser.add_argument("--epochs",        type=int,   default=MAX_EPOCHS)
    parser.add_argument("--batch",         type=int,   default=BATCH_SIZE)
    parser.add_argument("--lr",            type=float, default=LR)
    parser.add_argument("--lam-z",         type=float, default=LAM_Z)
    parser.add_argument("--lam-r",         type=float, default=LAM_R)
    parser.add_argument("--sigma-floor",   type=float, default=SIGMA_FLOOR)
    parser.add_argument("--warmup-epochs", type=int,   default=WARMUP_EPOCHS)
    parser.add_argument("--recon-ramp",    type=int,   default=RECON_RAMP,
                        help="Epochs over which λ_r ramps from 0 → LAM_R in Phase 2")
    parser.add_argument("--beta-max",      type=float, default=BETA_MAX,
                        help="Maximum KL weight β (annealed from 0 over --beta-epochs)")
    parser.add_argument("--beta-epochs",   type=int,   default=BETA_EPOCHS,
                        help="Epochs over which β is annealed from 0 → BETA_MAX in Phase 2")
    parser.add_argument("--patience",      type=int,   default=PATIENCE,
                        help="Early stopping patience (epochs without improvement)")
    parser.add_argument("--n-train",       type=int,   default=N_TRAIN_MAX,
                        help="Number of training SEDs to use from sed_train.h5")
    parser.add_argument("--lam-z-min",          type=float, default=LAM_Z_MIN,
                        help="λ_z floor during Phase 2 β-ramp (gives VAE gradient budget)")
    parser.add_argument("--lam-z-restore",      type=int,   default=LAM_Z_RESTORE,
                        help="Epochs to ramp λ_z back to full after β stabilises")
    parser.add_argument("--phase2-trunk-lr-frac", type=float, default=PHASE2_TRUNK_LR_FRAC,
                        help="LR multiplier for trunk/z_head at Phase 2 start")
    parser.add_argument("--phase2-vae-lr-frac",   type=float, default=PHASE2_VAE_LR_FRAC,
                        help="LR for vae_head at Phase 2 start (× base lr)")
    parser.add_argument("--z-boost-threshold", type=float, default=Z_BOOST_THRESHOLD,
                        help="Apply z-weight boost for training galaxies above this z")
    parser.add_argument("--z-boost-factor",    type=float, default=Z_BOOST_FACTOR,
                        help="Weight multiplier for z > --z-boost-threshold (1.0 = no boost)")
    parser.add_argument("--i-band-snr-min", type=float, default=I_BAND_SNR_MIN,
                        help="Minimum i-band SNR for galaxy inclusion (pass 0 or omit to "
                             "disable; default %(default)s)")
    parser.add_argument("--device",        default=DEVICE)
    parser.add_argument("--no-colors",  action="store_true",
                        help="Use raw magnitude features instead of colours")
    parser.add_argument("--no-euclid", action="store_true",
                        help="Use LSST-only photometry (6 bands, 24-dim encoder input)")
    parser.add_argument("--use-gaap", action="store_true",
                        help="Use GAAP 1.0-arcsec aperture mags for LSST bands "
                             "(Euclid columns are unchanged)")
    parser.add_argument("--model-version", choices=["old", "new"], default="old",
                        help="'old' = 3-head photoz_mlpvae_old (16-dim joint VAE); "
                             "'new' = photoz_mlpvae z-separated design (dedicated "
                             "z MLP head, 15-param VAE head conditioned on z)")
    args = parser.parse_args()

    use_colors = not args.no_colors
    use_euclid = not args.no_euclid
    use_gaap   = args.use_gaap
    n_bands    = 10 if use_euclid else 6
    m5sig_eff  = M_5SIG        if use_euclid else M_5SIG[:6]
    if use_gaap:
        mag_cols = GAAP_MAG_COLS      if use_euclid else LSST_GAAP_MAG_COLS
        err_cols = GAAP_ERR_COLS      if use_euclid else LSST_GAAP_ERR_COLS
    else:
        mag_cols = MAG_COLS           if use_euclid else LSST_MAG_COLS
        err_cols = ERR_COLS           if use_euclid else LSST_ERR_COLS

    out_dir = os.path.join(OUT_BASE, args.model_name)
    os.makedirs(out_dir, exist_ok=True)

    # ── Logging ───────────────────────────────────────────────────────────
    log_path   = os.path.join(out_dir, "train.log")
    sys.stdout = _Tee(sys.__stdout__, log_path)
    print(f"[{datetime.datetime.now():%Y-%m-%d %H:%M:%S}] Training started "
          f"(synthetic SEDs)")
    print(f"Model: {args.model_name}  |  device={args.device}  "
          f"|  use_colors={use_colors}  |  use_euclid={use_euclid}  "
          f"|  use_gaap={use_gaap}")
    print(f"Outputs → {out_dir}/")

    # ── Config ────────────────────────────────────────────────────────────
    config = dict(
        model_name     = args.model_name,
        data_source    = "synthetic_SEDs",
        use_colors     = use_colors,
        use_euclid     = use_euclid,
        use_gaap       = use_gaap,
        epochs         = args.epochs,
        batch          = args.batch,
        lr             = args.lr,
        lam_z          = args.lam_z,
        lam_r          = args.lam_r,
        sigma_floor    = args.sigma_floor,
        warmup_epochs  = args.warmup_epochs,
        beta_max       = args.beta_max,
        beta_epochs    = args.beta_epochs,
        recon_ramp     = args.recon_ramp,
        patience       = args.patience,
        seed           = SEED,
        device         = args.device,
        n_train        = args.n_train,
        n_val          = N_VAL_MAX,
        n_test         = N_TEST_MAX,
        n_zbins_weight        = N_ZBINS_WEIGHT,
        lam_z_min             = args.lam_z_min,
        lam_z_restore         = args.lam_z_restore,
        phase2_trunk_lr_frac  = args.phase2_trunk_lr_frac,
        phase2_vae_lr_frac    = args.phase2_vae_lr_frac,
        nmad_avg_window       = NMAD_AVG_WINDOW,
        z_boost_threshold     = args.z_boost_threshold,
        z_boost_factor     = args.z_boost_factor,
        synth_train_h5 = SYNTH_TRAIN_H5,
        synth_val_h5   = SYNTH_VAL_H5,
        m5sig          = M_5SIG.tolist(),
        calib_floor    = CALIB_FLOOR,
        i_band_snr_min = args.i_band_snr_min,
        speculator_dir = SPECULATOR_DIR,
        filter_dir     = FILTER_DIR,
        model_version  = args.model_version,
    )
    cfg_path = os.path.join(out_dir, "config.yaml")
    with open(cfg_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
    print(f"Config → {cfg_path}")

    # ── Reproducibility ───────────────────────────────────────────────────
    rng = np.random.default_rng(SEED)
    torch.manual_seed(SEED)

    # ── Load decoder (frozen) for photometry generation ───────────────────
    print("Loading Speculator + FilterConv …")
    if args.model_version == "new":
        from photoz_mlpvae.model.photoz_mlpvae import PhotozMLPVAE
    else:
        from photoz_mlpvae.model.photoz_mlpvae_old import PhotozMLPVAE
    model_dec = PhotozMLPVAE(SPECULATOR_DIR, FILTER_DIR).to(args.device)
    model_dec.eval()

    # ── Load SPS parameters from HDF5 ─────────────────────────────────────
    print(f"Loading theta: train ≤{args.n_train}  "
          f"val {N_VAL_MAX}  test {N_TEST_MAX} …")

    theta_tr  = load_theta_hdf5(SYNTH_TRAIN_H5, args.n_train, rng, start_row=0)
    theta_val = load_theta_hdf5(SYNTH_VAL_H5,   N_VAL_MAX,   rng, start_row=0)
    # Test set = last N_TEST_MAX rows of sed_val.h5
    with h5py.File(SYNTH_VAL_H5, "r") as _f:
        _n_val_total = _f["parameters"].shape[0]
    theta_te = load_theta_hdf5(
        SYNTH_VAL_H5, N_TEST_MAX, rng,
        start_row=_n_val_total - N_TEST_MAX
    )

    z_tr  = theta_tr[:, 0]
    z_val = theta_val[:, 0]
    z_te  = theta_te[:, 0]
    print(f"  Train {len(z_tr):,}  |  "
          f"z range [{z_tr.min():.2f}, {z_tr.max():.2f}]")
    print(f"  Val   {len(z_val):,}  |  "
          f"z range [{z_val.min():.2f}, {z_val.max():.2f}]")
    print(f"  Test  {len(z_te):,}   |  "
          f"z range [{z_te.min():.2f}, {z_te.max():.2f}]")

    # ── Generate noiseless photometry via Speculator ───────────────────────
    print("Generating noiseless photometry from Speculator …")
    t0 = time.time()
    mags_tr_clean  = generate_photometry_gpu(theta_tr,  model_dec, args.device)
    mags_val_clean = generate_photometry_gpu(theta_val, model_dec, args.device)
    mags_te_clean  = generate_photometry_gpu(theta_te,  model_dec, args.device)
    print(f"  Done in {time.time() - t0:.1f}s")
    print(f"  Mag range (train) i-band: "
          f"[{np.nanmin(mags_tr_clean[:, 3]):.1f}, "
          f"{np.nanmax(mags_tr_clean[:, 3]):.1f}]")

    # ── Restrict to active band set (no-op when use_euclid=True) ─────────
    mags_tr_clean  = mags_tr_clean[:,  :n_bands]
    mags_val_clean = mags_val_clean[:, :n_bands]
    mags_te_clean  = mags_te_clean[:,  :n_bands]

    # ── Add photometric noise ──────────────────────────────────────────────
    print("Assigning synthetic photometric errors (noiseless mags) …")
    mags_tr,  errs_tr,  mask_tr,  keep_tr  = add_photometric_errors(
        mags_tr_clean,  m5sig=m5sig_eff, i_band_snr_min=args.i_band_snr_min)
    mags_val, errs_val, mask_val, keep_val = add_photometric_errors(
        mags_val_clean, m5sig=m5sig_eff, i_band_snr_min=args.i_band_snr_min)
    mags_te,  errs_te,  mask_te,  keep_te  = add_photometric_errors(
        mags_te_clean,  m5sig=m5sig_eff, i_band_snr_min=args.i_band_snr_min)
    del mags_tr_clean, mags_val_clean, mags_te_clean

    for split, msk, keep in [("train", mask_tr, keep_tr),
                              ("val",   mask_val, keep_val),
                              ("test",  mask_te,  keep_te)]:
        print(f"  {split}: {keep.sum():,}/{len(keep):,} galaxies pass i-SNR≥{args.i_band_snr_min} cut"
              f"  |  {msk[keep].mean()*100:.1f}% band-detections")

    # Apply i-band SNR galaxy cut to all parallel arrays
    theta_tr  = theta_tr[keep_tr];   z_tr  = z_tr[keep_tr]
    mags_tr   = mags_tr[keep_tr];    errs_tr  = errs_tr[keep_tr];   mask_tr  = mask_tr[keep_tr]
    theta_val = theta_val[keep_val]; z_val = z_val[keep_val]
    mags_val  = mags_val[keep_val];  errs_val = errs_val[keep_val]; mask_val = mask_val[keep_val]
    theta_te  = theta_te[keep_te];   z_te  = z_te[keep_te]
    mags_te   = mags_te[keep_te];    errs_te  = errs_te[keep_te];   mask_te  = mask_te[keep_te]

    # ── Build DataFrames and 40-dim features ──────────────────────────────
    print("Building encoder features …")
    df_tr  = mags_to_dataframe(mags_tr,  errs_tr,  z_tr,  mag_cols, err_cols)
    df_val = mags_to_dataframe(mags_val, errs_val, z_val, mag_cols, err_cols)
    df_te  = mags_to_dataframe(mags_te,  errs_te,  z_te,  mag_cols, err_cols)

    (X_tr,  mags_tr,  errs_tr,  mask_tr,  z_tr,  scaler, col_med) = \
        build_features(df_tr,  use_colors=use_colors, use_euclid=use_euclid,
                       use_gaap=use_gaap, fit=True)
    (X_val, mags_val, errs_val, mask_val, z_val, _, _) = \
        build_features(df_val, use_colors=use_colors, use_euclid=use_euclid,
                       use_gaap=use_gaap, scaler=scaler, col_medians=col_med)
    (X_te,  mags_te,  errs_te,  mask_te,  z_te,  _, _) = \
        build_features(df_te,  use_colors=use_colors, use_euclid=use_euclid,
                       use_gaap=use_gaap, scaler=scaler, col_medians=col_med)

    # Append frac_detected + frac_blue_detected to break high-z trunk collapse.
    X_tr  = append_detection_features(X_tr,  mask_tr)
    X_val = append_detection_features(X_val, mask_val)
    X_te  = append_detection_features(X_te,  mask_te)
    print(f"  Encoder input dim: {X_tr.shape[1]}  "
          f"(base {X_tr.shape[1] - 2} + 2 detection features, {n_bands} bands)")

    zw_tr = compute_z_weights(z_tr, n_bins=N_ZBINS_WEIGHT)
    if args.z_boost_factor > 1.0:
        high_z_mask = z_tr > args.z_boost_threshold
        zw_tr[high_z_mask] *= args.z_boost_factor
        zw_tr /= zw_tr.mean()   # keep mean weight = 1 so lam_z scale is unchanged
        print(f"  z-boost ×{args.z_boost_factor:.1f} for z>{args.z_boost_threshold:.1f}: "
              f"{high_z_mask.sum():,} galaxies ({100*high_z_mask.mean():.1f}%)")
    print(f"  z-weights (train): min={zw_tr.min():.3f}  max={zw_tr.max():.3f}  "
          f"mean={zw_tr.mean():.3f}")

    # num_workers=0: avoids DataLoader worker shared-memory temp dirs (pymp-*)
    # that fail to clean up on NFS/Lustre when /tmp is full (EBUSY errno 16).
    tr_loader  = make_dataloader(X_tr,  mags_tr,  errs_tr,  mask_tr,  z_tr,
                                 zw_tr, args.batch, shuffle=True,  num_workers=0)
    val_loader = make_dataloader(X_val, mags_val, errs_val, mask_val, z_val,
                                 np.ones(len(z_val), dtype=np.float32),
                                 args.batch, shuffle=False, num_workers=0)
    te_loader  = make_dataloader(X_te,  mags_te,  errs_te,  mask_te,  z_te,
                                 np.ones(len(z_te),  dtype=np.float32),
                                 args.batch, shuffle=False, num_workers=0)

    # ── Model ─────────────────────────────────────────────────────────────
    model = PhotozMLPVAE(SPECULATOR_DIR, FILTER_DIR,
                         encoder_n_in=X_tr.shape[1]).to(args.device)
    n_enc = sum(p.numel() for p in model.encoder.parameters()
                if p.requires_grad)
    print(f"Encoder trainable parameters: {n_enc:,}")

    # ── Phase 1 optimizer: trunk + z-head + sigma_z-head; vae_head frozen ─
    print(f"\n── Phase 1: z-supervised warmup "
          f"({args.warmup_epochs} epochs, vae_head frozen) ──")
    model.encoder.freeze_vae_head()
    phase1_params = [p for p in model.encoder.parameters() if p.requires_grad]
    opt   = torch.optim.Adam(phase1_params, lr=args.lr, weight_decay=1e-5)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(
        opt, T_max=args.epochs, eta_min=1e-6)

    best_state    = {k: v.cpu().clone() for k, v in model.state_dict().items()}
    ckpt_path     = os.path.join(out_dir, "best.pt")
    best_nmad_avg = float("inf")
    nmad_window   = []
    patience_ctr  = 0
    phase2_started = False

    history = {k: [] for k in [
        "tr_total", "tr_z_sup", "tr_recon", "tr_kl", "tr_log_sigma_z",
        "val_total", "val_z_sup", "val_recon", "val_kl", "val_log_sigma_z",
        "val_sigma_nmad", "beta",
    ]}

    print(f"Training for up to {args.epochs} epochs\n")

    for epoch in range(1, args.epochs + 1):

        # ── Phase transition ───────────────────────────────────────────────
        if epoch == args.warmup_epochs + 1 and not phase2_started:
            print(f"\n── Phase 2: joint fine-tuning "
                  f"(epoch {epoch}, vae_head unfrozen, "
                  f"trunk lr ×{args.phase2_trunk_lr_frac}, "
                  f"vae lr ×{args.phase2_vae_lr_frac}) ──\n")
            model.encoder.unfreeze_vae_head()
            # Scale trunk/z_head/sigma_z_head LR, preserving Adam momentum.
            for pg in opt.param_groups:
                pg["lr"] *= args.phase2_trunk_lr_frac
            # Add vae_head as a new param group (learns from scratch).
            opt.add_param_group({
                "params":       list(model.encoder.vae_head.parameters()),
                "lr":           args.lr * args.phase2_vae_lr_frac,
                "weight_decay": 1e-5,
            })
            sched = torch.optim.lr_scheduler.CosineAnnealingLR(
                opt, T_max=args.epochs - epoch + 1, eta_min=1e-6)
            patience_ctr   = 0           # fresh patience budget for Phase 2
            best_nmad_avg  = float("inf")  # compete independently from Phase 1
            nmad_window    = []            # clear Phase 1 history
            phase2_started = True

        # ── Loss weights ───────────────────────────────────────────────────
        kl_epoch = max(0, epoch - args.warmup_epochs)

        if epoch <= args.warmup_epochs:
            lam_r_eff = 0.0
        elif epoch <= args.warmup_epochs + args.recon_ramp:
            lam_r_eff = args.lam_r * (epoch - args.warmup_epochs) / args.recon_ramp
        else:
            lam_r_eff = args.lam_r

        beta = min(args.beta_max,
                   args.beta_max * kl_epoch / max(args.beta_epochs - 1, 1))

        # λ_z drops at Phase 2 start to give the VAE gradient budget,
        # then restores linearly after β has stabilised.
        if epoch <= args.warmup_epochs:
            lam_z_eff = args.lam_z
        elif kl_epoch <= args.beta_epochs:
            lam_z_eff = args.lam_z_min
        elif kl_epoch <= args.beta_epochs + args.lam_z_restore:
            frac      = (kl_epoch - args.beta_epochs) / max(args.lam_z_restore, 1)
            lam_z_eff = args.lam_z_min + (args.lam_z - args.lam_z_min) * frac
        else:
            lam_z_eff = args.lam_z

        t0 = time.time()
        tr_loss  = run_epoch(model, tr_loader,  args.device, opt=opt,
                             lam_z=lam_z_eff, lam_r=lam_r_eff, beta=beta,
                             sigma_floor=args.sigma_floor,
                             use_nll_z=True)
        val_loss = run_epoch(model, val_loader, args.device, opt=None,
                             lam_z=lam_z_eff, lam_r=lam_r_eff, beta=beta,
                             sigma_floor=args.sigma_floor,
                             use_nll_z=True)

        model.eval()
        z_pred_val = []
        with torch.no_grad():
            for x_b, *_ in val_loader:
                _, z_mu, _ = model.predict_z(x_b.to(args.device), n_samples=1)
                z_pred_val.append(z_mu.cpu().numpy())
        z_pred_val = np.concatenate(z_pred_val)
        nmad = sigma_nmad(z_pred_val, z_val)

        sched.step()
        dt = time.time() - t0

        for k in ("total", "z_sup", "recon", "kl", "log_sigma_z"):
            history[f"tr_{k}"].append(tr_loss[k])
            history[f"val_{k}"].append(val_loss[k])
        history["val_sigma_nmad"].append(nmad)
        history["beta"].append(beta)

        # Rolling-average σ_NMAD smooths epoch-to-epoch noise.
        nmad_window.append(nmad)
        if len(nmad_window) > NMAD_AVG_WINDOW:
            nmad_window.pop(0)
        nmad_avg = float(np.mean(nmad_window))

        print(f"Ep {epoch:3d}/{args.epochs}  "
              f"tr={tr_loss['total']:.4f}  val={val_loss['total']:.4f}  "
              f"(z={val_loss['z_sup']:.4f} r={val_loss['recon']:.4f} "
              f"kl={val_loss['kl']:.4f})  "
              f"σ_NMAD={nmad:.4f}(avg={nmad_avg:.4f})  "
              f"σ_z={val_loss['log_sigma_z']:.3f}  "
              f"β={beta:.3f}  λ_z={lam_z_eff:.1f}  lam_r={lam_r_eff:.2f}  t={dt:.1f}s")

        if np.isnan(tr_loss["total"]) or np.isnan(val_loss["total"]):
            print(f"  NaN detected at epoch {epoch} — stopping.")
            break

        if not np.isnan(nmad_avg) and nmad_avg < best_nmad_avg:
            best_nmad_avg = nmad_avg
            best_state    = {k: v.cpu().clone()
                             for k, v in model.state_dict().items()}
            patience_ctr  = 0
            model.save(ckpt_path, scaler=scaler, col_medians=col_med)
            print(f"  ✓ New best avg σ_NMAD={nmad_avg:.4f} (inst={nmad:.4f})  "
                  f"saved → {ckpt_path}")
        else:
            patience_ctr += 1
            if patience_ctr >= args.patience:
                print(f"Early stopping (no improvement for {args.patience} epochs).")
                break

    # ── Final evaluation ──────────────────────────────────────────────────
    model.load_state_dict(best_state)
    model.eval()

    z_pred_te, z_std_te, z_samples_te = [], [], []
    with torch.no_grad():
        for x_b, *_ in te_loader:
            z_samps, z_mu, z_sd = model.predict_z(
                x_b.to(args.device), n_samples=200)
            z_pred_te.append(z_mu.cpu().numpy())
            z_std_te.append(z_sd.cpu().numpy())
            z_samples_te.append(z_samps.cpu().numpy())
    z_pred_te    = np.concatenate(z_pred_te)
    z_std_te     = np.concatenate(z_std_te)
    z_samples_te = np.concatenate(z_samples_te)

    dz_te = (z_pred_te - z_te) / (1.0 + z_te)
    bias_te, nmad_te, fout_te, rms_te, fcat_te = compute_metrics(dz_te, z_te)

    print(f"\n=== Test-set metrics ===")
    print(f"  σ_NMAD  : {nmad_te:.4f}")
    print(f"  Bias    : {bias_te:.4f}")
    print(f"  Outliers: {fout_te*100:.2f}%")
    print(f"  RMS     : {rms_te:.4f}")
    print(f"  f_cat   : {fcat_te*100:.2f}%")

    # ── Save predictions ──────────────────────────────────────────────────
    pred_df = pd.DataFrame({
        "z_true":  z_te,
        "z_pred":  z_pred_te,
        "z_std":   z_std_te,
        "delta_z": (z_pred_te - z_te) / (1.0 + z_te),
    })
    # Also save the true SPS parameters so downstream analyses can use them
    for j, name in enumerate(PARAM_NAMES_FULL):
        pred_df[f"theta_true_{name}"] = theta_te[:, j]
    pred_path = os.path.join(out_dir, "test_predictions.csv")
    pred_df.to_csv(pred_path, index=False)
    print(f"  Predictions → {pred_path}")

    # ── Select failure-case galaxies for diagnostic plots ─────────────────
    # Same z_true / z_pred targets as train.py
    _targets = [
        (0.5, 0.5,  "good_lowz"),
        (3.5, 3.5,  "good_highz"),
        (0.5, 1.5,  "mild_overest"),
        (0.5, 3.0,  "severe_overest"),
        (3.5, 2.5,  "mild_underest"),
        (3.5, 1.0,  "severe_underest"),
    ]
    sel_idx = []
    for zt, zp, _ in _targets:
        score = np.abs(z_te - zt) + np.abs(z_pred_te - zp)
        sel_idx.append(int(np.argmin(score)))

    sel_labels      = [lbl for _, _, lbl in _targets]
    sel_z_true      = z_te[sel_idx]
    sel_z_pred      = z_pred_te[sel_idx]
    sel_X           = X_te[sel_idx]
    sel_mags        = mags_te[sel_idx]
    sel_errs        = errs_te[sel_idx]
    sel_mask        = mask_te[sel_idx]
    sel_theta_true  = theta_te[sel_idx]   # (N_sel, 16) – all true SPS params

    print("\n── Failure-case diagnostics ──")
    for lbl, zt, zp in zip(sel_labels, sel_z_true, sel_z_pred):
        print(f"  {lbl:<15s}  z_true={zt:.3f}  z_pred={zp:.3f}")

    # ── Corner plots – with ALL 16 true SPS parameter truth values ─────────
    plot_corner_posteriors(
        model, sel_X, sel_z_true, sel_z_pred,
        sel_labels, args.device,
        os.path.join(out_dir, "corner"),
        n_samples=2000,
        theta_true=sel_theta_true,   # gold truth lines for all 16 params
    )

    # ── SED reconstruction panels ─────────────────────────────────────────
    plot_sed_reconstructions(
        model, sel_X, sel_mags, sel_errs, sel_mask,
        sel_z_true, sel_z_pred, sel_labels,
        args.device,
        os.path.join(out_dir, "test_sed_reconstructions.png"),
        theta_true=sel_theta_true,
    )

    # ── Standard figures ──────────────────────────────────────────────────
    plot_scatter(z_te, z_pred_te,
                 os.path.join(out_dir, "test_scatter.png"),
                 title=f"{args.model_name}  test  σ_NMAD={nmad_te:.3f}")
    plot_redshift_hist(z_te, z_pred_te,
                       os.path.join(out_dir, "test_zdist.png"))
    plot_metrics_vs_zpred(z_te, z_pred_te,
                          os.path.join(out_dir, "test_metrics_vs_z.png"))
    events = [
        (args.warmup_epochs,
         "Phase 2: VAE unfrozen, λ_r & β begin ramping"),
        (args.warmup_epochs + args.recon_ramp,
         "λ_r fully on"),
        (args.warmup_epochs + args.beta_epochs,
         "β fully on"),
    ]
    plot_curves(history, os.path.join(out_dir, "train_curves.png"), events=events)
    plot_metrics_paper_style(z_te, z_pred_te, args.model_name,
                             os.path.join(out_dir, "test_metrics_paper_style.png"))
    plot_pit(z_te, z_pred_te, z_samples=z_samples_te,
             save_path=os.path.join(out_dir, "test_pit.png"),
             title=args.model_name)

    print(f"\nDone. Best avg σ_NMAD={best_nmad_avg:.4f}")
    print(f"[{datetime.datetime.now():%Y-%m-%d %H:%M:%S}] Training finished")
    if isinstance(sys.stdout, _Tee):
        sys.stdout.close()
        sys.stdout = sys.__stdout__


if __name__ == "__main__":
    main()
